# Generated by Django 6.0.3 on 2026-03-15 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('pauta', models.TextField(blank=True)),
                ('texto', models.TextField()),
                ('conclusoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='people.pessoa')),
            ],
            options={
                'verbose_name': 'Nota de Reunião',
                'verbose_name_plural': 'Notas de Reunião',
                'ordering': ['-data'],
            },
        ),
    ]
