# Generated by Django 6.0.3 on 2026-03-15 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('oferta', 'Oferta'), ('doacao', 'Doação'), ('inscricao', 'Inscrição'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encontro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='events.encontro')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='people.pessoa')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('material', 'Material'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encontro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='events.encontro')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ['-data'],
            },
        ),
    ]
