# Generated by Django 6.0.3 on 2026-03-15 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ministério',
                'verbose_name_plural': 'Ministérios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MembroMinisterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministerios', to='people.pessoa')),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='ministries.ministerio')),
            ],
            options={
                'verbose_name': 'Membro do Ministério',
                'verbose_name_plural': 'Membros dos Ministérios',
                'unique_together': {('ministerio', 'pessoa')},
            },
        ),
    ]
