# Generated by Django 6.0.3 on 2026-03-15 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('membro', 'Membro'), ('visitante', 'Visitante'), ('inativo', 'Inativo')], default='visitante', max_length=20)),
                ('e_servo', models.BooleanField(default=False)),
                ('cargo_nucleo', models.CharField(blank=True, choices=[('coordenador', 'Coordenador(a)'), ('secretario', 'Secretário(a)'), ('tesoureiro', 'Tesoureiro(a)'), ('lider', 'Líder'), ('outro', 'Outro')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
    ]
